version: '3.9'

services:
  api:
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  migrator:
    build:
      context: .
    container_name: migrator
    command: sh -c "node build/bin/console.js migration:run && node build/bin/console.js db:seed"
    depends_on:
      - db
    networks:
      - my-network